export enum HW5_Events {
    PLAYER_MOVE = "PlayerMove",
    PLAYER_JUMP = "PlayerJump",
    PLAYER_HIT_SWITCH = "PlayerHitSwitch",
    SPIKES_FALL = "SpikesFall",
    PLAYER_HIT_HEALTH = "PlayerHitHealth",
    PLAYER_HIT_SPIKES = "PlayerHitSpikes",
    /*PLAYER_HIT_BALLOON = "PlayerHitEBalloon"*/PLAYER_HIT_MINE = "PlayerHitMine",
    /*BALLOON_POPPED = "BalloonPopped"*/MINE_EXPLODED = "MineExploded",
    PLAYER_ENTERED_LEVEL_END = "PlayerEnteredLevelEnd",
    UPDATE_GRAVITY = "UpdateGravity",
    SHARK_HIT_PLAYER = "SharkHitPlayer",
    SPIKE_HIT_SHARK = "SpikeHitShark",
    LEVEL_START = "LevelStart",
    LEVEL_END = "LevelEnd",
    PLAYER_KILLED = "PlayerKilled",
    SUIT_COLOR_CHANGE = "SuitColorChange",
}